# Pre-commit configuration for Music Streaming Churn Prediction Project
# Ensures code quality, formatting, and security before commits

repos:
  # Pre-commit hooks for general file maintenance
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: '\.csv$|\.json$'
      - id: end-of-file-fixer
        exclude: '\.csv$|\.json$|\.pkl$'
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=10000']  # Max 10MB files
      - id: check-case-conflict
      - id: mixed-line-ending
        args: ['--fix=lf']

  # Ruff for linting and formatting (via uv)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9  # Use latest stable version
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
        types_or: [python, pyi]
        additional_dependencies: ["uv"]  # ensure uv available
      - id: ruff-format
        types_or: [python, pyi]
        additional_dependencies: ["uv"]

  # Security scanning for Python dependencies (run under uv)
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ['-r', '.', '--exclude', 'tests/']
        language: system  # run via system so uv can handle deps
        entry: uv run bandit

  # Jupyter notebook cleaning
  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
        files: '\.ipynb$'

  # Docker linting
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        args: ['--ignore', 'DL3008', '--ignore', 'DL3009']

  # YAML/Markdown formatting (via uv-prettier)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [yaml, markdown]
        exclude: '\.github/.*'
        additional_dependencies: ["uv"]

# Configuration for pre-commit
default_language_version:
  python: python3.11

# Enable uv as default package installer for hooks
default_install_hook_types: [pre-commit, pre-push]
default_stages: [commit]
default_language: system

# CI configuration
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: [bandit, hadolint-docker]  # Skip slow hooks in CI
  submodules: false
